spring.application.name=checkpost
spring.datasource.url=jdbc:postgresql://localhost:5432/checkpost
spring.datasource.username=checkpost
spring.datasource.password=checkpost
spring.jpa.hibernate.ddl-auto=update
spring.data.redis.host=localhost
spring.data.redis.port=6379